### ISSUE TITLE
Unable to load blockchain

### ISSUE THREAD

**Issue by samlspencer** [Multibit-Legacy/multibit#165]
Hi, last night I initiated a transfer and the coins showed up but did not become usable. After 6+ hours of waiting I hit the button to reset the blockchain transactions and the worst happened. It now says that my wallet has 0 coins and that the file is corrupted as seen below. 

"com.google.bitcoin.store.BlockStoreException Corrupted block store: could not find chain head"

Trying to reset does not work and has been stuck in "synchronizing" for a little over 2 hrs.

Any help will be much appreciated.

**Comment by sipsapa** [comment]
I m having this same problem, except when I go to user/library/application support - there is no multibit folders - i should say, I have defo installed multiit and it shows and opens in my applications folder, there is just no files in app support - what am i doing wrong - help would be greatly appreciated

**Comment by gary-rowe** [comment]
They might be hidden folders. Have a look here: https://multibit.org/en/help/v0.5/help_support_missingWallets.html
