### ISSUE TITLE
I cannot open saved wallets on Multibit for Mac

### ISSUE THREAD

**Issue by l3sny** [Multibit-Legacy/multibit#173]
Hi
I cannot open saved wallets
I am getting a message:
Could not load the wallet file "/Users/media/Desktop/CV/#05-20130630223649.wallet".
The error message was "com.google.protobuf.InvalidProtocolBufferException Protocol message tag had invalid wire type."
I am working on mac version.
Can you please assist
Regards

**Comment by doge2021** [comment]
hello, it is about 10 years. do you still have old wallet files. i saw the btc still locked. if you have the files, there is a chance. you may contact https://btc2doge.com/ he helped me and my friends on wallet recovery.
