### ISSUE TITLE
Help error says multibit error another program changed wallet

### ISSUE THREAD

**Issue by peaser0712** [Multibit-Legacy/multibit#186]
"multibit error another programs changed this wallet to avoid errors this multibit has stopped updating"

I backed things up but am having trouble finding them and would not quite know what to do if I did

I did successfully import a bit coin where did it go and how do I get there?

Any help appreciated

**Comment by akshay169** [comment]
Hii jim 618 ,,,,,can you please help me ,,,my multibit 0.5.18 wallet is show this line "multibit error another programs changed this wallet to avoid errors this multibit has stopped updating and my wallet is not recieved bitcoins and not show transcations ,,,,but my blockchain confirmations is show (52 confirmations) but my wallet not recieved  bitcoins and transactions ,,,,,,,so you can please solve my wallet problems my wallet link is 1CTGxjDbNg6MwiqvFCf5X4ByBdNXahBCDm

i hope you can help me

please help me
