### ISSUE TITLE
Listen for connections on port 8333

### ISSUE THREAD

**Issue by lbensaad** [Multibit-Legacy/multibit#206]
I noticed that multibit does not listen on port 8333 as bitcoin-qt does. is it possible, how to add that in the code or where to change?

**Comment by ekkis** [comment]
if that is the case, why does Multibit prompt me to accept incoming network connections every time I run it?

**Comment by gary-rowe** [comment]
MultiBit opens port 8330 to listen for other instances of MultiBit starting. The new instance then hands over the Bitcoin URI details to the currently running instance and closes down.

See http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers and search "MultiBit".

**Comment by ekkis** [comment]
ohh… I see.  that’s how it handles not running twice and invocations from links on the web.  so if I disallow it, that won’t work. thanks for the reply! that should be documented somewhere!
