### ISSUE TITLE
Loose my password

### ISSUE THREAD

**Issue by 1singularity1** [Multibit-Legacy/multibit#215]
Hi,

i'm in panic since 2 hours. I tried to check my password into multibit and it doesn't work anymore. I was sure of my password but i can not decrypt my wallet anymore. Please I need help. I can prove that i am the owner of the wallet.

Thanks in advance,
David

**Comment by clementin02** [comment]
@1singularity1 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
