### ISSUE TITLE
API Feature Suggestion

### ISSUE THREAD

**Issue by mmcc1** [Multibit-Legacy/multibit#259]
Guys,

First, excellent work.  

I would like to see an API that can send and receive commands.  I am thinking of a type of payment processer API.

Here is the scenario:

I offer a product for sale, along with a bitcoin link for payment.  I save a transaction id to my database.  When Multibit receives a payment, it passes the details to my server via POST, along with authentication details (TLS/SSL of course).

I look at the label for the transaction id and I can then update my site.  This could also be done in batches on a schedule.

To send a payment, I would send a command to Multibit, along with some authentication details.  If it could support scheduling of payments as a batch operation (either by API command or offline file), that would be great.

**Comment by jeanleonino** [comment]
How is the status on that so far?
