### ISSUE TITLE
FORGOTTEN PASSWORD

### ISSUE THREAD

**Issue by Billwilliam** [Multibit-Legacy/multibit#265]
Hi I have a Multibit wallet that is very secure so secure in fact i cannot send my funds to buy certain things i would like! 
I have tried tens of passwords with caps no caps etc and none are working! i have about  1.5 bitcoins in the account and it is really annoying that i cannot infact use them at all seeing as i finally got them transferred to me last night! 
i would be more than happy to donate if this issue could be resolved even if a nice computer hacker could get this back he/she would be rewarded

**Comment by clementin02** [comment]
@Billwilliam 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]

**Comment by doge2021** [comment]
you can try https://btc2doge.com/ if you still locked
