### ISSUE TITLE
my multibit wallet

### ISSUE THREAD

**Issue by boba89** [Multibit-Legacy/multibit#290]
Have you got this wallet data on your end 

1Kfysutx8SPZ3gfaemKcDAEYkV6QEUzF7k

that was the wallet where my bitcoins were sorted in, and iv lost the data can you help??????

**Comment by clementin02** [comment]
@boba89 did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
