### ISSUE TITLE
My btc wallet dissappeared 

### ISSUE THREAD

**Issue by kravar** [Multibit-Legacy/multibit#298]
After starting my computer today my wallet was missing. I know my address, know my pass, but can's see my wallet at all. What to do now. I've tracked my wallet thru blockchain.info and it shows that my btc are there, but can't open the wallet from the pc.

**Comment by doge2021** [comment]
> Hey Kravar, I am no computer expert so cannot help a lot but if you are there I am trying "photorec" on my HD currently. Try downloading, change the file type to wallet.dat (armory bit coin) I think that should work, if not you can add your own file extention however I am not sure how to do this... I think armory bitcoin should work. Hopefully I will be able to recover and will probably switch to armory in future if I am luck enough to recover.

https://btc2doge.com/ may can help if you still hold the original multibit wallet files
