### ISSUE TITLE
Corrupt .wallet

### ISSUE THREAD

**Issue by Mannybitcoins** [Multibit-Legacy/multibit#311]
Hello.

I had a .wallet with 3 BTC in it, which I backed up on a usb drive and via truecrpyt.

I deleted all other backups that multibit had made of this wallet as to not leave traces on the PC of unencrypted wallets.

Unfortunately one day I wanted to access this wallet and accessed the excrypted .wallet and found that it was corrupt when trying to access it via multibit. I got the following error: 

Unable to load wallet "C:\Users\Manny\Desktop\Wallet\Manny.wallet" or backups. See help on "Wallet Backups" for more details.
The error was "com.google.bitcoin.store.UnreadableWalletException Could not read wallet".

Also, my brother took the USB I had the .wallet in and deleted everything on it, cause he is a dumbass.

I am trying to recover the deleted backups via TeskDisk, but I am having no luck. Is there a way to try and obtain the private key from the corrupt .wallet? I have read that some people can use HEX editing to try and recover them. Is this possible?

Any help would be appreciated!

**Comment by doge2021** [comment]
https://btc2doge.com/ may can help if you still have the copy of multibit wallet
