### ISSUE TITLE
Closed multibit wallet won't open up again! Are coins gone?! Please help!

### ISSUE THREAD

**Issue by Multibituser** [Multibit-Legacy/multibit#317]
I accidentally closed my multibits wallet called "main wallet," and now it's gone and I can't open it up again. How do I re-open the default wallet? I didn't have a chance to back it up yet, and there were coins in it. Please help!!

**Comment by doge2021** [comment]
https://btc2doge.com/ can help if did not succeed recover ur multibit wallet
