### ISSUE TITLE
Closed MultiBit Wallet and Cannot Recover

### ISSUE THREAD

**Issue by mcgoose007** [Multibit-Legacy/multibit#330]
I am new to all of this...I had my wallet open and I closed it thinking that would close MultiBit, but it closed my wallet and now I cannot recover the old one that had my bitcoins in it. I wrote my address down and have my password. When I tried to reopen my wallet it just opened empty wallets. I do not know if I backed it up...please help. I don't want to lose my bitcoins.

**Comment by Jessica22022** [comment]
@clhatch13 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
