### ISSUE TITLE
Multibit Wallet Password Corruption

### ISSUE THREAD

**Issue by Tranpinter** [Multibit-Legacy/multibit#333]
Multibit wallet password that worked previously will now not work. I am positive I have made no mistakes with typing in the password and as I have said the password worked last time I used it. Is there a solution to this or are my $500 odd worth of coins out of reach for good?

**Comment by Jessica22022** [comment]
@Tranpinter 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
