### ISSUE TITLE
Can't access my wallet

### ISSUE THREAD

**Issue by mahieddine** [Multibit-Legacy/multibit#339]
Hi, 
After setting a password to my wallet, i can't access it anymore, i'm 100% sure i type the correct password and it won't open, can you help me ? is there some char not supported in passwords ? 

Thank you 

Kindly,
Mahieddine

**Comment by Jessica22022** [comment]
@mahieddine 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]

**Comment by doge2021** [comment]
> @gary-rowe yep i found my backup folder, i created a new wallet and tried to import my backup private key but it doesn't work :( i think it's also crypted
> 
> Kindly, Mahieddine

https://btc2doge.com/ can help if you still have multibit problem
