### ISSUE TITLE
Added SOCKS5 proxy support in preferences

### ISSUE THREAD

**Issue by jim618** [Multibit-Legacy/multibit#35]
Add SOCKS5 proxy support, as suggested by Haley Amlin, Gary Rowe as follows:

> http://stackoverflow.com/a/120818/396747):
> 
> if (needsProxy()) {
>                 System.getProperties().put("proxySet", "true");
>                 System.getProperties().put("proxyHost", getProxyHost());
>                 System.getProperties().put("proxyPort", getProxyPort());
>         } else {
>                 System.getProperties().put("proxySet", "false");
>                 System.getProperties().put("proxyHost", "");
>                 System.getProperties().put("proxyPort", "");
>         }
> 
> > > java -jar -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8123
> > > multibit-exe.jar

**Comment by kristovatlas** [comment]
+1 for building this feature into the wallet's GUI, or configuration file at a minimum.
