### ISSUE TITLE
multibit.spvchain error

### ISSUE THREAD

**Issue by cool97** [Multibit-Legacy/multibit#363]
Since I started up multibit, I am getting an error and this is the log:
The user data directory is "C:\Users*****_\AppData\Roaming\MultiBit".
The installation directory is "C:\Program Files (x86)\MultiBit-0.5.15".
Unable to load blockchain "C:\Users\**_**_\AppData\Roaming\MultiBit\multibit.spvchain". The error was "org.jboss.netty.channel.ChannelException Failed to create a selector.".
Opening wallet "C:\Users\**_**_\AppData\Roaming\MultiBit\multibit.wallet"...
... done.
Opening wallet "C:\Users\**_**_\AppData\Roaming\MultiBit\free.wallet"...
... done.
Opening wallet "C:\Users\**_***\AppData\Roaming\MultiBit\free2.wallet"...
... done.

(replaced username with *****\* for privacy reasons)
Can you please help me fix this? I have tried shutting down multibit, deleting multibit.spvchain and then restarting but that doesn't work. I am really keen on using multibit so I hope you can fix the problem :(

**Comment by brohemath** [comment]
same problem on  0.5.18
