### ISSUE TITLE
Bitcoins Missing after reset BlockChain and Transactions

### ISSUE THREAD

**Issue by harmanbhogal** [Multibit-Legacy/multibit#367]
Hello Sir/Mam,

I had bought my first bitcoin on 26NOV13 via VirWox. The BitCoins were appearing in my multibit wallet until today. I verified the transaction address on blockinfo and I found the same count of BTC associated with the transaction details. 

Yesterday, I sent few bitcoins to BTC-E and it was in pending state with a white square box under transactions. The remaining BitCoins were still visible in my wallet. I checked the address in blockinfo and it told me no transaction found. This worried me so I read solution blog relevant to this problem and the suggestion was to reset the transactions with "restart blockchain and transaction" button.

After doing so, the send transaction ( the one with white square) was removed but my wallet balance also bacame 0 BTC. 

Please help resolve the matter and bring back the BTCs back to my wallet. 

Thanks

**Comment by simdie** [comment]
Hi, thanks for your help. BUT:
My experience, was a transaction sent to my btc address wallet. (Note; i created my wallet address on blockchain.info, and i dont have any wallet software on my pc, so every transaction is done on blockchain.info site.), The merchant sent the funds equivalent to 320 usd 2 consecutive times.
The funds appeared on my blockchain.info wallet account, and was unconfirmed for a period of 2 hours. 
After this period, the whole funds and the unconfirmed transaction details disappeared from my blockchain.info wallet account, and from the blockchain.info network (the transaction was not listed any where again).
I am stucked, and was so bored, cant find my wallet, and i dont know what to do as i dont have a wallet software on my pc. I only operate my btc transaction on the blockchain.info online wallet account.

How do i scan back my bitcoins ?
How do i get back my bitcoins, ?
Please i really need a help on this issue.
thanks

**Comment by jim618** [comment]
@simdle If you are solely using blockchain.info for sending/ receiving your bitcoins then you will need to talk to their support people. This issues database is for MultiBit Classic and MultiBit HD only. As you mention that you created the wallet address on blockchain.info then it will be their software that you will need to work with, not ours.

I hope that is clear.
