### ISSUE TITLE
Lost BTC with multi bit reset blockchain

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit#370]
Hey there, I'm really having a difficult time right now trying to figure out what happened to my btc. I had a transaction that took all night, was frozen. It was for .08 btc. In my wallet before i sent that, i had 3 btc. after i sent the 0.08 btc, my spendable amount was only 1.4 btc ( this was weird to me ) now today it was still frozen at only seen by 1 peer, so i reset the block chain for yesterday. the transaction for 0.08 btc is gone, but i still only have 1.4 btc spendable. i sent these away to another wallet because i didn't know what was going on and now my balance is zero and i can't send anymore. where are my other btc ?

**Comment by brohemath** [comment]
Same problem here. Tried upgrading to 5.19 to hope it would fix the problem, no joy. 

Unable to load blockchain, error com.google.bitcoin.store.BlockStoreException Corrupted block store

Turned VPN off, reset modem, restarted computer, upgraded to 5.19, nothing has worked.

brohem
