### ISSUE TITLE
Please help? Lost 6.5 bitcoins today, bad wallet error

### ISSUE THREAD

**Issue by mountainjam** [Multibit-Legacy/multibit#382]
Hello Jim,
I had sent a PM on bitcointalk today not realizing that I could use github.  Here is my issue:
Today I made a new bitcoin receiving address and sent myself 6.5 bitcoins from btc-e; they arrived just fine and then I went off to lunch.  All was fine, but when I came home I noticed that my computer appeared to have restarted.  Upon opening multibit, I saw I had 0 bitcoins.  
My wallet file cannot be opened now due to this error:
The error message was "com.google.protobuf.InvalidProtocolBufferException Protocol message contained an invalid tag (zero)."

I get this same error whether I open the wallet file or its backup which was automatically made.  I have a backup from 9/7/13 that works, but it does not have the new receiving address I made today and it appears my 6.5 bitcoins are gone forever. 

I can send any log files and anything else you might need.  Thanks!

**Comment by pattersonn** [comment]
@mountainjam 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]

**Comment by doge2021** [comment]
> At this point I'm trying to decrypt my wallet file with openssl to maybe find a private key for the newly made address that appears to be gone forever. However, I get an error when trying. Am I on the right track? This is the command I'm using: C:\OpenSSL-Win64\bin>openssl enc -d -p -aes-256-cbc -a -in multibit-20131204124056.wallet -out outputfile.txt -pass pass:password error reading input file
> 
> There was no password on my wallet, so I'm assuming I can use anything for the password. I'm pretty bummed out by the situation and hope I can get some help.
@mountainjam 
reach https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/ if you still hold the wallet file
