### ISSUE TITLE
Generated invalid address '1FYMZEHnszCHKTBdFZ2DLrUuk3dGwYKQxh'

### ISSUE THREAD

**Issue by shangri** [Multibit-Legacy/multibit#403]
Bug report
  Operating System: windows 7 unlimited x64
  MultiBit Version: 0.5.15
I'm generated more new addresses a few weeks ago in multibit. Оne of the addresses is 1FYMZEHnszCHKTBdFZ2DLrUuk3dGwYKQxh, Today i see payment to this adress 0.0098 btc. I can see in my wallet 0.0098 btc, but i can't export private key. How did it happen that I have address with payments? What should I do?

**Comment by peterwillcn** [comment]
1HT7xU2Ngenf7D4yocz2SAcnNLW7rK8d4E
