### ISSUE TITLE
multibit btc recovery

### ISSUE THREAD

**Issue by bobbauer12** [Multibit-Legacy/multibit#496]
i format my laptop 3 hrs ago and i cant find all my btc again when i installed multibit, does it means that i lost my $205

**Comment by pattersonn** [comment]
@bobbauer12 

did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
