### ISSUE TITLE
password on wallet

### ISSUE THREAD

**Issue by roofLe** [Multibit-Legacy/multibit#497]
I downloaded the newest version on multibit from multibit.org. I opened it and saw my wallet. I clicked receive and transferred btc to my wallet. While playing around I made a new wallet and noticed it didn't have a lock on it. So I clicked on the lock to see what it was and noticed it brought up a help page with information about the password. I never entered a password to encrypt my wallet. I've also never used multibit on my computer. Trying to figure out how when I started the program it created a wallet with a password on it that I don't know or never entered.

**Comment by pattersonn** [comment]
@roofLe 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]
