### ISSUE TITLE
Sending BTC from Multibit , all sends never seen by peers

### ISSUE THREAD

**Issue by helpplease23** [Multibit-Legacy/multibit#524]
Everytime I try to send, my sent btc is not seen by any peers.  Then I have to refresh the blockchain to even see my balance in btc.  I tried to export my private keys to blockchain, but blockchain says that there is an error decrypting, and the password is incorrect.....there IS NO password on the exported file.....

**Comment by RaghavSood** [comment]
For posterity, the blog post linked above is still available on archive.org: https://web.archive.org/web/20140704184820/https://multibit.org/blog/2014/04/28/private-key-safety-improvements.html

The multibit site now redirects to the GitHub repo.
