### ISSUE TITLE
Multibit isnt showing my correct balance - 

### ISSUE THREAD

**Issue by ceasarpolar** [Multibit-Legacy/multibit#594]
Multibit is not showing my correct balance, I went on reset to blockchain and it deleted all my transactions and showing me a balance of 0 BTC. 
I went on the help section, then I exported my private key unencrypted. Then went on blockchain created a new wallet, then on import key, copied pasted my key, then my balance was still showing 0 BTC so I copied pasted my private key on blockchain, and still my balance is not showing up!!! 
So : 
- I exported my private keys from multibit to my computer
- opened it with notepad, grabbed my private key, it started by L, deleted the dates and useless info in the key, kept only the 52 characters that started with L, for some reasons I had 2 sets of L keys, the first one worked the other no. 
- On the first one, blockchain prompted me to input password, I did, and my balance is still showing 0 BTC where my orginal balance was 2.07 BTC. 

I have no clue where is my bitcoins, I am in total perdition, I tried to contact the support of multibit, they have asked me to go through the help section where I went through it 1000 times yesterday. 

For any newbie out there, if you want to keep your nerves at a normal level STAY AWAY FROM MULTIBIT! 
The support is really slow, I send them 7 emails and they answered with one saying dont plug your bitcoin address in the key section but your unencrypted key, and go to the help section. Really Jim, really ??? I have already did that, and please I know what it s the difference between a wallet and a private key, EVEN tho I am a newbie. 

Despite all this, I still need HELP badly to recover my bitcoins!!! 
PLEASE HELP ME RECOVER THEM.

**Comment by mrbatpower** [comment]
I have this problem I had around 1500$ balance in my wallet and now multibit classic is showing my balance zero and my computer clock is correct. how to solve this issue to get my balance back?

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time.

**Comment by Carl1Leon** [comment]
Shocking experience! I would label MultiBit wallets as criminal activity. They marketed a product that claimes to be able to securely store and transfer Bitcoins. This would really be misleading and deceptive conduct 1) My wallet won't even show the correct balance. 2)Then the private keys wont reflect the full bitcoin held amount. 3)Restoring the block chain might not synchronise living you in limbo. 

You cant manufacture faulty products and then apparently walk away saying it's time for us to move on the product will not longer be supported. No matter what version you might have classic or HD this should work no matter what. 

If you cant deliver and fulfill this operations you shouldn't be marketing the wallet in the first place as you are putting clients money at risk. Whether its multibit, keepkey or Kenneth (Heutmaker) Hodler the product provider is liable to compensate clients if it malfunctions or if it doesnt do what it is supposed to do.

I await your urgent assistance.
