### ISSUE TITLE
MultiBit Fail to Restore?

### ISSUE THREAD

**Issue by jakkuh** [Multibit-Legacy/multibit#788]
I apparently changed my password althought I do not remember doing this but my password doesn't open the wallet anymore. I go to restore password and it gets stuck at "Working" forever. Whats wrong with multibit! :( 

![fail to restore](https://cloud.githubusercontent.com/assets/14115855/26342194/ed502786-3f4b-11e7-8ae2-4477d9d3e352.png)

**Comment by tobakk** [comment]
I got same issue after the password Im very sure about didn't work anymore
Using Linux version 4.10.6-1-ARCH

**Comment by DirkVDW2** [comment]
Here same issue... If -on another computer- I try to retreive the password, I get something like this..,
![image](https://user-images.githubusercontent.com/29356926/27012747-b8af247e-4ed6-11e7-9776-c9bdc9b7b684.png)
My password is readible at the end... but the rest of the string is rubbish. 
Probalby this is the reason why I cannot acces my wallet anylonger. 

I tried this now on 3 Windows installations. 
And now also on an UBUNTU. 

I have my wallet addres, private key, words etc.
How can I transfer my wallet to another application ?

@Multibit ... get your stuff with regards to passwords bugfree. This is too important !!

**Comment by DirkVDW2** [comment]
Hi Dirk,
Thank you for reaching out to us.

I am sorry you are experiencing issues with your wallet.

A known bug in Multibit is causing the error you are experiencing. Your funds remain safe and recoverable.

Please recover your wallet with using Breadwallet or Simple Bitcoin wallet. They are both mobile wallets that work great with Multibit wallet word recovery. Breadwallet (https://breadwallet.com/) is available on App store and simple bitcoin wallet (https://play.google.com/store/apps/details?id=com.btcontract.wallet&hl=en) is for Android.

 We are currently working on other solutions for this issue and will advise when this is available.


Sincerely,

Anna Rudenko

KeepKey, LLC
www.keepkey.com

**Comment by Georgeh0h** [comment]
@tobakk 
@jakkuh 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [walletsrecoveryservice@gmail.com

**Comment by Jenova55** [comment]
@jakkuh 
@tobakk 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : [[walletsrecoveryservice@gmail.com]

**Comment by doge2021** [comment]
you may reach [www.btc2doge.org](http://www.btc2doge.org/)
