### ISSUE TITLE
64 bit Java on Windows 7 not seen

### ISSUE THREAD

**Issue by jim618** [Multibit-Legacy/multibit#89]
From mailing list:
A cursory search for the terms java and/or 64 bit didn't bring anything. So I apologize if it this has been covered. I have a 64 bit java installation but multibit can't find it. And before the suggestion comes that I should downgrade to 32 bit java, there is a reason I need the 64 bit support. I ... require over 4 gigabytes of ram.

**Comment by Bjonnfesk** [comment]
I won't speak to MultiBit or JWrapper, but the exact same issue is present in JSmooth-wrapped applications. It will spit an error along the lines of "Java has not been found on your computer, would you like to download it?", even though the Java bin directory is added to the path variable and works fine with other applications. As with MultiBit, installing 32-bit Java alongside 64-bit works as a workaround.
